In [29]:
import os
import pandas as pd
import csv

In [30]:
GESTURES = {'rest', 'open_hand', 'fist', 'thumbs_up'}
TRIAL_NUMS = range(1, 11)

DATA_DIR_PATH = os.path.join('..', 'data', 'my_data', 'subject_one', 'individual_files')
COMBINED_CSV_PATH = os.path.join('..', 'data', 'my_data', 'subject_one', 'combined_subject_one.csv')

In [31]:
os.makedirs(os.path.dirname(DATA_DIR_PATH), exist_ok=True)
def get_csv_paths(root_path=DATA_DIR_PATH, subjects=[1], gestures=GESTURES, trials=TRIAL_NUMS):
    csv_paths = []
    for gesture in gestures:
        for trial in trials:
            for subject in subjects:
                file_name = f"{gesture}_subject_{subject}_left_trial_{trial:02d}b.csv"
                file_path = os.path.join(root_path, file_name)
                csv_paths.append(file_path)
    return csv_paths

def save_combined_df(save_path=COMBINED_CSV_PATH, data_path=DATA_DIR_PATH, subjects=[1], gestures=GESTURES, trials=TRIAL_NUMS):
    combined_df = pd.DataFrame()
    csv_paths = get_csv_paths(root_path=data_path, subjects=subjects, gestures=gestures, trials=trials)
    for path in csv_paths:
        df = pd.read_csv(path)
        combined_df = pd.concat([combined_df, df], ignore_index=True)
    combined_df.to_csv(save_path, index=False)
    return combined_df

combined_df = save_combined_df()
combined_df['trial'].value_counts()



trial
1     192799
2     176238
8     175436
4     173398
3     173274
5     172262
6     170450
9     168762
7     168286
10    167318
Name: count, dtype: int64

In [ ]:
import numpy as np
print(np.load('./results/my_data/test_confusion_matrix_0124.npy'))

[[4079  176    0   65]
 [ 147 4005   14  192]
 [   0    6 2386    0]
 [ 867   95    0 1430]]


In [22]:
TRIAL_ROWS = [145610, 146001, 149283, 146669, 146094, 145263, 145131, 144981, 148812, 146135, 149150, 148322]
NUM_ROWS = sum(TRIAL_ROWS)
NUM_ROWS

1761451