In [1]:
import os
import pandas as pd
import csv

In [2]:
GESTURES = {'rest', 'open_hand', 'fist', 'index'}
TRIAL_NUMS = range(1, 33)

DATA_DIR_PATH = os.path.join('..', 'data', 'my_data', 'subject_one', 'individual_files')
COMBINED_CSV_PATH = os.path.join('..', 'data', 'my_data', 'subject_one', 'combined_subject_one.csv')

In [ ]:
os.makedirs(os.path.dirname(DATA_DIR_PATH), exist_ok=True)
def get_csv_paths(root_path=DATA_DIR_PATH, subjects=[1], gestures=GESTURES, trials=TRIAL_NUMS):
    csv_paths = []
    for gesture in gestures:
        for trial in trials:
            # trials 1-11 are only rest and open hand
            if trial in range(1, 11) and (gesture == "index" or gesture =="fist"):
                continue
            for subject in subjects:
                file_name = f"{gesture}_subject_{subject}_left_trial_{trial:02d}b.csv"
                file_path = os.path.join(root_path, file_name)
                csv_paths.append(file_path)
    return csv_paths

def save_combined_df(save_path=COMBINED_CSV_PATH, data_path=DATA_DIR_PATH, subjects=[1], gestures=GESTURES, trials=TRIAL_NUMS):
    combined_df = pd.DataFrame()
    csv_paths = get_csv_paths(root_path=data_path, subjects=subjects, gestures=gestures, trials=trials)
    for path in csv_paths:
        df = pd.read_csv(path)
        combined_df = pd.concat([combined_df, df], ignore_index=True)
    combined_df.to_csv(save_path, index=False)
    return combined_df

combined_df = save_combined_df()

trial
12    182056
15    180228
18    180178
17    179399
19    177775
16    177428
29    176713
13    175323
32    173087
20    172932
24    172064
31    171754
26    171670
22    171532
27    171052
30    170768
28    170694
14    170117
23    169213
21    168678
25    168648
1     100083
2      90045
11     89373
3      87692
4      86928
5      85639
9      84930
7      84834
8      84782
10     84144
6      82988
Name: count, dtype: int64

In [88]:
trial_vc = combined_df['trial'].value_counts()
trial_pairs = sorted(list(zip(trial_vc.index, trial_vc.values)))
trial_counts = [elt[1] for elt in trial_pairs]

trial_pairs_w_index = trial_pairs[:11]
w_index_counts = [elt[1] for elt in trial_pairs_w_index]
print(f"Total data rows: {sum(trial_counts)}")
print(f"Data rows for trials w/ index {sum(w_index_counts)}")

Total data rows: 4612747
Data rows for trials w/ index 961438


In [ ]:
import numpy as np
print(np.load('./results/my_data/log_reg_test_confusion_matrix_0124.npy'))
print(np.load('./results/my_data/rf_test_confusion_matrix_0124.npy'))


[[1037   25    0   17]
 [  20  522    0  526]
 [   0  166  886   12]
 [ 462   21   13  560]]


In [22]:
TRIAL_ROWS = [145610, 146001, 149283, 146669, 146094, 145263, 145131, 144981, 148812, 146135, 149150, 148322]
NUM_ROWS = sum(TRIAL_ROWS)
NUM_ROWS

1761451